### ISSUE TITLE
rev4 source code/keymap

### ISSUE THREAD

**Issue by nec4** [0xCB-dev/0xCB-1337#6]
Hello, love the design of the macropad and it was fun to build. The macropad works fine when I use the hex provided in the rev4 release, but for some reason I cannot use the default keymap using QMK:

```
qmk flash -kb 0xcb/1337 -km default
```

Everything compiles and flashes just fine, but the OLED is different and the keymap seems broken (half the keys don't register and those that do are not sending the codes they are supposed to). I can re-flash the rev4 hex file and it works fine again, so I am pretty sure there is no issue with my soldering or the board. Am I using an old version of the PCB that is not compatible with the keymaps in the current QMK repo?

**Comment by Conor-Burns** [comment]
Hi, 
The rev 4 vial code is not upstream in qmk
Please try this instead https://github.com/0xCB-dev/keeb-firmware-source/tree/main/vial/1337

**Comment by nec4** [comment]
Awesome, thanks!
